### ISSUE TITLE
Full pipeline tuning?

### ISSUE THREAD

**Issue by S-C-H** [Ibotta/sk-dist#13]
Does DistGridSearchCV allow for full pipeline tuning? (it doesn't appear to unless I am missing something?)

It would be pretty useful to tune some of the feature extraction parts e.g. number of ngram -hashed features.

- would just like to state: well done with this project. It's excellent and I appreciate that care and time has been taken to ensure it works as intended.

**Comment by denver1117** [comment]
Hi! I've added this example: https://github.com/Ibotta/sk-dist/pull/14

Pipelines totally work with `DistGridSearchCV`. Are these examples what you had in mind? Feel free to comment on the PR with questions or suggestions for further examples.

**Comment by S-C-H** [comment]
Thank you! I did find it hidden in an example earlier but definitely good to have this stand alone.
