### ISSUE TITLE
_index_param_value not defined when searching params for CatBoostClassifier

### ISSUE THREAD

**Issue by Stuart-D-King** [Ibotta/sk-dist#26]
Getting a `NameError: name '_index_param_value' is not defined` error while fitting `DistRandomizedSearchCV` on a **CatBoostClassifier** model. Here is some sample code:
```
params = {
    'depth': [4,6,8],
    'learning_rate': [0.02,0.05,0.1],
    'l2_leaf_reg': [1,5,10],
    'random_strength': [1,5,10],
    'bagging_temperature': [1,5,10],
    'one_hot_max_size': [2,10,50],
    'logging_level': ['Silent'],
    'use_best_model': [True],
    'od_type': ['Iter'],
    'od_wait': [20],
    'eval_metric': ['F1'],
    'iterations': [2000],
    'scale_pos_weight': [scale_multiplier],
    'colsample_bylevel': [0.6,0.8,1],
    'random_state': [42],
    'cat_features': [categorical_features_indices]
    }

model = DistRandomizedSearchCV(
    CatBoostClassifier(),
    params, sc, cv=3, scoring='roc_auc', n_iter=10, verbose=1
    )

model.fit(X_train, y_train, eval_set=(X_validation, y_validation))
```

Possibly an error on my part. But the error message implies `_index_param_value` needs to be defined, which appears to be missing in the source code. 

I am able to run a `DistRandomizedSearchCV` search if I drop the `eval_set` and other overfitting detection parameters. However, it would be great to be able to utilized CatBoost's native overfitting detection.

**Comment by denver1117** [comment]
This has been addressed by this PR: https://github.com/Ibotta/sk-dist/pull/27 which has been merged and is reflected in version `0.1.5`

Thanks for the bug report.
