### ISSUE TITLE
[problem] does sk-dist support lightgbm or xgboost with sklearn API?

### ISSUE THREAD

**Issue by chjq201410695** [Ibotta/sk-dist#3]

**Comment by cfrazier91** [comment]
Hi @chjq201410695 I just added documentation for supporting xgboost models with sk-dist. It can be found in this PR https://github.com/Ibotta/sk-dist/pull/4

**Comment by denver1117** [comment]
As far as LightGBM goes, technically anything conforming to the sklearn estimator API will work. LightGBM requires [more involved dependencies](https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#linux) that would need to be installed on the spark nodes through the bootstrap. This is likely possible, but not something we've tested.
