### ISSUE TITLE
Spark local-mode testing for Travis CI

### ISSUE THREAD

**Issue by denver1117** [Ibotta/sk-dist#7]
**Is your feature request related to a problem? Please describe.**
The current test suite is meant to run only in a python environment after setup/installation. This doesn't allow testing Spark functionality in a spark environment.

**Describe the solution you'd like**
Ideally, we'd have either a separate test suite, or the entire test suite would be meant to run only in a Spark environment, setup locally by Travis CI.

**Additional context**
Most functionality can be tested without Spark, but the Spark parallelization itself cannot be tested, and Spark version compatibility cannot be tested. This would make the testing suite more robust to both `sk-dist` code changes and Spark/PySpark version changes/updates.

**Comment by cfrazier91** [comment]
Solved with https://github.com/Ibotta/sk-dist/pull/10
